import { GetSecretValueCommand, SecretsManagerClient } from '@aws-sdk/client-secrets-manager'

/**
 * The signing secret Better Auth uses for cookies, OTP hashes and the JWKS
 * private key at rest (issue 157). Generated by CDK into `makerbay/auth`
 * and never seen by a person. Same shape as the Stripe and Resend readers:
 * cached for the execution environment, never logged.
 */
const sm = new SecretsManagerClient({})
let cached: { secret: string } | undefined

export async function authSecrets(): Promise<{ secret: string }> {
  if (cached) return cached
  const arn = process.env.AUTH_SECRET_ARN
  if (!arn) throw new Error('auth_not_configured')
  let raw = ''
  try {
    raw = (await sm.send(new GetSecretValueCommand({ SecretId: arn }))).SecretString ?? ''
  } catch (err) {
    console.error('could not read auth secret', { name: err instanceof Error ? err.name : 'unknown' })
    throw new Error('auth_not_configured')
  }
  let parsed: Record<string, string>
  try {
    parsed = JSON.parse(raw)
  } catch {
    throw new Error('auth_not_configured')
  }
  const secret = parsed.secret ?? ''
  if (secret.length < 32) {
    console.error('auth secret unusable', { fieldsPresent: Object.keys(parsed), length: secret.length })
    throw new Error('auth_not_configured')
  }
  cached = { secret }
  return cached
}
